'use client';

import { useEffect, useState, useRef } from 'react';
import { Plus, Edit2, Download, X, Loader2, Map as MapIcon } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { supabase } from '@/lib/supabaseClient';
import type { Location, Tattoo } from '@/types';
import { MAP_DEFAULT_CENTER, MAP_DEFAULT_ZOOM } from '@/lib/constants';

// Note: In a real robust admin, we'd use Leaflet here to pick lat/lng visually.
// For brevity, using simple number inputs. The user requested Map picker in the plan,
// so let's add a basic Leaflet map for picking coordinates.

import dynamic from 'next/dynamic';

const LocationPickerMap = dynamic(
  () => import('@/components/LocationPickerMap').then(mod => mod.LocationPickerMap),
  { ssr: false, loading: () => <div className="h-64 bg-ink-950 flex items-center justify-center animate-pulse">Loading map...</div> }
);

export default function AdminLocationsPage() {
  const [locations, setLocations] = useState<Location[]>([]);
  const [tattoos, setTattoos] = useState<Tattoo[]>([]);
  const [loading, setLoading] = useState(true);
  
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  
  // Form State
  const [tattooId, setTattooId] = useState('');
  const [lat, setLat] = useState<number>(MAP_DEFAULT_CENTER[0]);
  const [lng, setLng] = useState<number>(MAP_DEFAULT_CENTER[1]);
  const [hintText, setHintText] = useState('');
  const [isActive, setIsActive] = useState(true);
  const [saving, setSaving] = useState(false);
  
  // QR Download State
  const [qrLocation, setQrLocation] = useState<Location | null>(null);
  const qrRef = useRef<SVGSVGElement>(null);

  const fetchData = async () => {
    setLoading(true);
    
    const [{ data: locData }, { data: tatData }] = await Promise.all([
      supabase.from('locations').select('*, tattoo:tattoos(title)').order('created_at', { ascending: false }),
      supabase.from('tattoos').select('id, title, is_active').order('title')
    ]);

    if (locData) setLocations(locData as Location[]);
    if (tatData) setTattoos(tatData as Tattoo[]);
    
    setLoading(false);
  };

  useEffect(() => {
    fetchData();
  }, []);

  const openForm = (loc?: Location) => {
    if (loc) {
      setEditingId(loc.id);
      setTattooId(loc.tattoo_id);
      setLat(loc.lat);
      setLng(loc.lng);
      setHintText(loc.hint_text || '');
      setIsActive(loc.is_active);
    } else {
      setEditingId(null);
      setTattooId('');
      setLat(MAP_DEFAULT_CENTER[0]);
      setLng(MAP_DEFAULT_CENTER[1]);
      setHintText('');
      setIsActive(true);
    }
    setIsFormOpen(true);
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!tattooId) return;
    setSaving(true);

    const payload = {
      tattoo_id: tattooId,
      lat,
      lng,
      hint_text: hintText || null,
      is_active: isActive,
    };

    if (editingId) {
      await supabase.from('locations').update(payload).eq('id', editingId);
    } else {
      // qr_uuid is auto-generated by the DB default (uuid_generate_v4())
      await supabase.from('locations').insert(payload);
    }

    setSaving(false);
    setIsFormOpen(false);
    fetchData();
  };

  const handleDownloadQR = () => {
    if (!qrRef.current || !qrLocation) return;
    const svgData = new XMLSerializer().serializeToString(qrRef.current);
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    const img = new Image();
    
    img.onload = () => {
      // Scale up for high-res print
      canvas.width = img.width * 4;
      canvas.height = img.height * 4;
      ctx?.drawImage(img, 0, 0, canvas.width, canvas.height);
      const pngFile = canvas.toDataURL('image/png');
      
      const downloadLink = document.createElement('a');
      downloadLink.download = `inkquest-qr-${qrLocation.tattoo?.title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${qrLocation.qr_uuid.substring(0,8)}.png`;
      downloadLink.href = pngFile;
      downloadLink.click();
    };
    
    img.src = 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(svgData)));
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="font-display text-3xl text-ink-100 tracking-widest mb-1">Locations</h2>
          <p className="text-ink-400 font-ui text-sm uppercase tracking-widest">Manage QR sticker spots</p>
        </div>
        <button
          onClick={() => openForm()}
          className="flex items-center gap-2 px-4 py-2 bg-gold-600 hover:bg-gold-500 text-ink-950 font-ui text-xs uppercase tracking-widest rounded transition-colors"
        >
          <Plus size={16} /> New Location
        </button>
      </div>

      {loading ? (
        <div className="flex h-32 items-center justify-center">
          <div className="w-8 h-8 border-2 border-gold-500 border-t-transparent rounded-full animate-spin" />
        </div>
      ) : (
        <div className="bg-ink-900 border border-ink-800 rounded-xl overflow-hidden overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-ink-950 text-ink-400 font-ui text-[10px] uppercase tracking-widest">
                <th className="p-4 font-normal">Tattoo</th>
                <th className="p-4 font-normal">Coordinates</th>
                <th className="p-4 font-normal">Hint Text</th>
                <th className="p-4 font-normal">Status</th>
                <th className="p-4 font-normal text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-ink-800 font-body text-sm text-ink-300">
              {locations.map((loc) => (
                <tr key={loc.id} className="hover:bg-ink-800/50 transition-colors">
                  <td className="p-4">{loc.tattoo?.title || 'Unknown Tattoo'}</td>
                  <td className="p-4 font-ui text-xs text-ink-500">
                    {loc.lat.toFixed(5)}, {loc.lng.toFixed(5)}
                  </td>
                  <td className="p-4 truncate max-w-[200px]">{loc.hint_text || '-'}</td>
                  <td className="p-4">
                    <span className={`px-2 py-1 rounded text-[10px] font-ui uppercase tracking-wider ${
                      loc.is_active ? 'bg-green-900/30 text-green-500 border border-green-900' : 'bg-red-900/30 text-red-500 border border-red-900'
                    }`}>
                      {loc.is_active ? 'Active' : 'Hidden'}
                    </span>
                  </td>
                  <td className="p-4 text-right">
                    <div className="flex items-center justify-end gap-3">
                      <button 
                        onClick={() => setQrLocation(loc)} 
                        className="text-ink-400 hover:text-gold-500 transition-colors tooltip-trigger"
                        title="Download QR"
                      >
                        <Download size={16} />
                      </button>
                      <button 
                        onClick={() => openForm(loc)} 
                        className="text-ink-400 hover:text-gold-500 transition-colors tooltip-trigger"
                        title="Edit Location"
                      >
                        <Edit2 size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Form Modal */}
      {isFormOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-ink-950/90 backdrop-blur-sm">
          <div className="w-full max-w-3xl bg-ink-900 border border-ink-700 rounded-xl flex flex-col max-h-[90vh]">
            <div className="flex items-center justify-between p-4 border-b border-ink-800">
              <h2 className="font-display text-xl text-gold-500 tracking-widest">{editingId ? 'Edit' : 'New'} Location</h2>
              <button onClick={() => setIsFormOpen(false)} className="text-ink-400 hover:text-ink-100"><X size={20}/></button>
            </div>
            
            <form onSubmit={handleSave} className="flex-1 overflow-y-auto p-6 space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div>
                    <label className="block text-ink-400 text-[10px] font-ui uppercase tracking-widest mb-1">Select Tattoo *</label>
                    <select required value={tattooId} onChange={e => setTattooId(e.target.value)} className="w-full bg-ink-950 border border-ink-700 rounded p-2 text-sm text-ink-100">
                      <option value="">-- Choose --</option>
                      {tattoos.map(t => (
                        <option key={t.id} value={t.id}>{t.title} {t.is_active ? '' : '(Inactive)'}</option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-ink-400 text-[10px] font-ui uppercase tracking-widest mb-1">Hint Text</label>
                    <textarea rows={3} value={hintText} onChange={e => setHintText(e.target.value)} placeholder="e.g. Look behind the statue..." className="w-full bg-ink-950 border border-ink-700 rounded p-2 text-sm text-ink-100 font-body" />
                  </div>
                  <div className="flex gap-4">
                    <div className="flex-1">
                      <label className="block text-ink-400 text-[10px] font-ui uppercase tracking-widest mb-1">Latitude *</label>
                      <input required type="number" step="any" value={lat} onChange={e => setLat(parseFloat(e.target.value))} className="w-full bg-ink-950 border border-ink-700 rounded p-2 text-sm text-ink-100 font-ui" />
                    </div>
                    <div className="flex-1">
                      <label className="block text-ink-400 text-[10px] font-ui uppercase tracking-widest mb-1">Longitude *</label>
                      <input required type="number" step="any" value={lng} onChange={e => setLng(parseFloat(e.target.value))} className="w-full bg-ink-950 border border-ink-700 rounded p-2 text-sm text-ink-100 font-ui" />
                    </div>
                  </div>
                  <div className="flex items-center gap-2 pt-2">
                    <input type="checkbox" id="locActive" checked={isActive} onChange={e => setIsActive(e.target.checked)} className="accent-gold-500" />
                    <label htmlFor="locActive" className="text-sm text-ink-300 font-ui uppercase tracking-widest">Active (can be found)</label>
                  </div>
                </div>

                <div className="flex flex-col">
                  <label className="block text-ink-400 text-[10px] font-ui uppercase tracking-widest mb-1">Pick Location</label>
                  <div className="flex-1 border border-ink-700 rounded-xl overflow-hidden min-h-[250px]">
                     <LocationPickerMap 
                        center={[lat, lng]} 
                        onLocationSelect={(l, ln) => { setLat(l); setLng(ln); }} 
                     />
                  </div>
                  <p className="text-ink-500 text-[10px] font-ui uppercase tracking-widest mt-2">Click on the map to set coordinates</p>
                </div>
              </div>

              <div className="flex justify-end gap-3 pt-6 border-t border-ink-800">
                <button type="button" onClick={() => setIsFormOpen(false)} className="px-4 py-2 text-ink-300 font-ui text-xs uppercase tracking-widest hover:text-ink-100">Cancel</button>
                <button type="submit" disabled={saving} className="flex items-center justify-center min-w-[120px] px-6 py-2 bg-gold-600 hover:bg-gold-500 text-ink-950 font-ui text-xs uppercase tracking-widest rounded disabled:opacity-50">
                  {saving ? <Loader2 size={16} className="animate-spin" /> : 'Save Location'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* QR Download Modal */}
      {qrLocation && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-ink-950/95 backdrop-blur-sm">
          <div className="bg-ink-900 border border-ink-700 rounded-xl p-8 max-w-sm w-full text-center">
            <h3 className="font-display text-2xl text-gold-500 tracking-widest mb-1">QR Code</h3>
            <p className="text-ink-300 font-ui text-sm mb-6">{qrLocation.tattoo?.title}</p>
            
            <div className="bg-white p-4 rounded-xl mx-auto inline-block mb-6 shadow-[0_0_30px_rgba(201,168,76,0.3)]">
              <QRCodeSVG
                value={`${typeof window !== 'undefined' ? window.location.origin : ''}/scan/${qrLocation.qr_uuid}`}
                size={200}
                bgColor="#ffffff"
                fgColor="#000000"
                level="Q"
                marginSize={1}
                imageSettings={{
                  src: '/icons/icon-192.png',
                  height: 40,
                  width: 40,
                  excavate: true,
                }}
                ref={qrRef}
              />
            </div>
            
            <p className="text-ink-500 text-[10px] font-ui break-all mb-6">
              ID: {qrLocation.qr_uuid}
            </p>
            
            <div className="flex gap-3">
              <button onClick={() => setQrLocation(null)} className="flex-1 py-3 text-ink-300 border border-ink-700 rounded font-ui text-xs uppercase tracking-widest hover:border-ink-500 transition-colors">
                Close
              </button>
              <button onClick={handleDownloadQR} className="flex-1 py-3 bg-gold-600 text-ink-950 rounded font-ui text-xs uppercase tracking-widest hover:bg-gold-500 transition-colors flex items-center justify-center gap-2">
                <Download size={14} /> PNG
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
